server:
  port: 8081
spring:
  application:
    name: weiss-app
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
github:
  client_id:
  clientSecret:
  accessTokenUri:
  userAuthorizationUrl:
  prefix:
vk:
  client_id:
  clientSecret:
  redirectUri:
  userAuthorizationUrl:
  accessTokenUrl:
  prefix: VK
fb:
  client_id:
  clientSecret:
  redirectUri:
  userAuthorizationUrl:
  accessTokenUrl:
  prefix: FB
